# The Basics

## Load the Numpy and start

In [2]:
import numpy as np

In [19]:
#1-D array
# a = np.array([1,2,3]) originally size is 4 bytes or int 32
a = np.array([1,2,3], dtype='int16')
print(f'array->{a}, no. of elements->{a.size}, data type->{a.dtype}, size in bytes->{a.itemsize}')
# get dimensions
print(f'dimension --> {a.ndim}')
# get shape
print(f'Shape --> {a.shape}')

array->[1 2 3], no. of elements->3, data type->int16, size in bytes->2
dimension --> 1
Shape --> (3,)


In [20]:
#2-D array
b = np.array([[1,2,3],[4,5,6]])
print(f'array->{b}, no. of elements->{b.size}, data type->{b.dtype}, size in bytes->{b.itemsize}')
# get dimensions
print(f'dimension --> {b.ndim}')
# get shape (rows, columns)
print(f'Shape --> {b.shape}')

array->[[1 2 3]
 [4 5 6]], no. of elements->6, data type->int64, size in bytes->8
dimension --> 2
Shape --> (2, 3)


## Accessing/ Changing specific elements, rows, columns etc.

In [21]:
c = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(c)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [28]:
# get a specific element [r, c]
print(c[0,4])
print(c[1,3])


5
8


In [31]:
# get a specific row [r,:]
c[1,:]

array([5, 6, 7, 8, 9])

In [32]:
#get a specific column [:,c]
c[:,3]

array([4, 8])

In [39]:
# Getting specific range [r, startindex:endindex:steps]
c[0, 0:-2:2]

array([1, 3])

In [43]:
# change specific element
c[1,2] = 8
print(c)

[[1 2 3 4 5]
 [5 6 8 8 9]]


In [44]:
#changing a whole column
c[:,4] = 10
print(c)

[[ 1  2  3  4 10]
 [ 5  6  8  8 10]]


## Working with 3d arrays

In [60]:
d = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [54]:
#Accessing elements (work outside in)
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [61]:
# changing elements
print(d[:,1,0])
d[:,1,0] = [10,10]
print(d)

[3 7]
[[[ 1  2]
  [10  4]]

 [[ 5  6]
  [10  8]]]


## Initializing different types of arrays

In [72]:
# All zeroes matrix
# (Number of elements for 1D)
print(np.zeros(2))
# (number of rows, number of columns) for 2D
print(np.zeros((2,3)))
# (number of matrices, number of rows, number of columns) for 3D
np.zeros((4,3,5))



[0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [74]:
#All ones matrix
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [75]:
#any other number

In [81]:
e = np.full((2,3,3), 53)
print(e)

[[[53 53 53]
  [53 53 53]
  [53 53 53]]

 [[53 53 53]
  [53 53 53]
  [53 53 53]]]


In [82]:
#copying another shape and printing different number
np.full(e.shape, 15)

array([[[15, 15, 15],
        [15, 15, 15],
        [15, 15, 15]],

       [[15, 15, 15],
        [15, 15, 15],
        [15, 15, 15]]])

In [86]:
#random decimal numbers 
#--> directly pass shape in this not inside a tuple like(2,3) no ((2,3))
np.random.rand(2,3)

array([[0.89097032, 0.16453802, 0.42268607],
       [0.127516  , 0.49597758, 0.54569599]])

In [105]:
#random integer values (start, end, size)
np.random.randint(-10,10, size=(3,3))

array([[-9, -2,  5],
       [ 3,  6, -3],
       [ 2, -3,  4]])

In [107]:
# the identity is a square matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [117]:
# Repeating elements
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)
r2 = np.repeat(arr, 3, axis=1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


## Q1)Try making this shape 
    1 1 1 1 1
    1 0 0 0 1
    1 0 9 0 1
    1 0 0 0 1
    1 1 1 1 1


In [138]:

one = np.ones((5,5))
one[1:4,1:4] = 0 
one[2,2]=9
print(one)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [139]:
# When copying array use .copy() method otherwise,
# if we update the copied one then the original one will also be updated
a = np.array([1,2,3])
b=a.copy()
b[1]= 4 
print(a)
print(b)


[1 2 3]
[1 4 3]


# Mathematics

## Basics

### Add,sub...

In [140]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [145]:
# Addition
add = a + 2
print(add)
#subtraction
sub = a-2
print(sub)
#product
pro = a*2
print(pro)
#divide
div = a/2
print(div)
#modulus
mod = a%2
print(mod)

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[1 0 1 0 1]


In [148]:
# adding two arrays
a = np.array([0,5,10,15])
b = np.array([1,6,11,16])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

[ 1 11 21 31]
[-1 -1 -1 -1]
[  0  30 110 240]
[0.         0.83333333 0.90909091 0.9375    ]
[ 0  5 10 15]


### Power

In [151]:

a = np.array([1,2,3])
print(a**2) #a^2 
print(a**3) #a^3

[1 4 9]
[ 1  8 27]


### Trignometric functions

In [155]:
a = np.array([1,2,3])
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]


## Linear Algebra (more function on numpy docs)

In [163]:
# For Matrix multiplication remember rows of 1st should be equal to columns of 2nd
a = np.full((5,3), 1)
print(a)
b = np.full((3,2), 3)
print(b)
# Here a*b doent work because size is different of the matrices
# inseat we use numpy matrix multiply formula (np.matmul(a,b))
np.matmul(a,b)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[3 3]
 [3 3]
 [3 3]]


array([[9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9]])

In [165]:
# finding the determinant
c = np.identity(3)
np.linalg.det

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

## Stats

In [168]:
stats = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(stats)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [171]:
print(f'min --> {np.min(stats)}')
print(f'max --> {np.max(stats)}')

min --> 1
max --> 10


In [175]:
print(np.min(stats, axis=0))
print(np.max(stats, axis=1))

[1 2 3 4 5]
[ 5 10]


In [180]:
print(np.sum(stats)) # sum of all elements
print(np.sum(stats, axis=0)) # sum column wise
print(np.sum(stats, axis=1)) # sum row wise

55
[ 7  9 11 13 15]
[15 40]


In [184]:
np.mean(stats)
np.median(stats)

5.5

## Reorganizing arrays

In [192]:
# Number of elements in before and after should be equal 
# cannot change 4x2 matrix into 4x3 or 2x3
before = np.array([[0,2,4,6], [1,3,5,7]])
print(before)

after = before.reshape(4,2)
print(after)
after = before.reshape(2,2,2)
print(after)

[[0 2 4 6]
 [1 3 5 7]]
[[0 2]
 [4 6]
 [1 3]
 [5 7]]
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


In [203]:
# vertically stacking matrix
m1 = np.array([1,2,3,4])
m2 = np.array([5,6,7,8])

vertical = np.vstack([m1,m2])
print(vertical)
vertical = np.vstack([m1,m2,m2,m2,m1])
print(vertical)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


In [213]:
# horizontal stacking matrix
h1 = np.ones((2,4))
h2 = np.zeros((2,2))


hori = np.hstack((h1,h2))
print(hori)

TypeError: 'list' object is not callable

# Extras and Imp!

## Load data from file

In [226]:
filedata = np.genfromtxt('file.txt', delimiter=',')
print(filedata)
print('...................................................................')
filedata = filedata.astype('int16')
print(filedata)

[[  1.   2.   3. 234.   4.   6.  57.   5.  65.   7.  46.   4.   6.   4.]
 [  9.   9.   8.  73.   4.   4.   6.   3.   5. 745.   6.  45.   6.   8.]
 [  2.   4.  nan   3.  64.   5.  64.  57.   6. 756.   7. 467.  35.  nan]
 [ 45.  34.   6.  34.  34.   5. 324.  23.  43. 754.   6.   4.   3.   7.]]
...................................................................
[[  1   2   3 234   4   6  57   5  65   7  46   4   6   4]
 [  9   9   8  73   4   4   6   3   5 745   6  45   6   8]
 [  2   4   0   3  64   5  64  57   6 756   7 467  35   0]
 [ 45  34   6  34  34   5 324  23  43 754   6   4   3   7]]


## Boolean masking and advance indexing

In [227]:
filedata < 10

array([[ True,  True,  True, False,  True,  True, False,  True, False,
         True, False,  True,  True,  True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True,
        False,  True, False,  True,  True],
       [ True,  True,  True,  True, False,  True, False, False,  True,
        False,  True, False, False,  True],
       [False, False,  True, False, False,  True, False, False, False,
        False,  True,  True,  True,  True]])

In [228]:
filedata[filedata >100]

array([234, 745, 756, 467, 324, 754], dtype=int16)

In [236]:
np.any(filedata>500, axis=1) #any value in column or row

array([False,  True,  True,  True])

In [234]:
np.all(filedata<10, axis=0) #all values in column

array([False, False,  True, False, False,  True, False, False, False,
       False, False, False, False,  True])

## Q2) In the given matrix:
    [ 1  2  3  4  5]
    [ 6  7  8  9 10]
    [11 12 13 14 15]
    [16 17 18 19 20]
    [21 22 23 24 25]
    [26 27 28 29 30]

    1)Find matrix ([[11,12], [16,17]])
    2)Locate these numbers in matrix[ 2  8 14 20]
    3)Locate these numbers in matrix[4,5],[24, 25],[29, 30]

In [239]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10],
         [11,12,13,14,15], [16,17,18,19,20],
         [21,22,23,24,25],[26,27,28,29,30]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [243]:
print(a[2:4, 0:2])

[[11 12]
 [16 17]]


In [245]:
print(a[[0,1,2,3],[1,2,3,4]])

[ 2  8 14 20]


In [252]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])